const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "2000",
      title: "Professional diploma of level A2 Trade and Accounting",
      desc: "Graduated at Lycée de KICUKIRO A.P.A.D.E",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2003",
      title: "D T I (Diploma of technician in data processing for management)",
      desc: "Graduated at Complexe D’enseignement SAINT MICHEL de DAKAR-SENEGAL",
    },
    {
      id: 3,
      category: "education",
      icon: "icon-graduation",
      year: "2007",
      title: "Bachelor of Computer Science Networks and Telecommunications",
      desc: "Graduated at International IT Academy of Dakar SUP’INFO",
    },
    {
      id: 4,
      category: "education",
      icon: "icon-graduation",
      year: "2008",
      title: "Master of Computer Science in Computer Networks and Telecommunications (OBTAINED WITH HONORS)",
      desc: "Graduated at International IT Academy of Dakar SUP’INFO",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "January 2006",
      title: "Web Designer",
      desc: "Design of the X@E project and Software Testing of INTERACTIVE X@E project",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "September – October 2006",
      title: "Internship to the SONATEL",
      desc: "centre of supervision and management of the BACKBONE of Senegal and the VSAT Station of Gandour",
    },
    {
      id: 7,
      category: "experience",
      icon: "icon-briefcase",
      year: "December 2008 - September 2009",
      title: "Trainor at the University of Dakar",
      desc: "Trainor at the CENTIC Center of Cheikh Anta Diop (UCAD II) University of Dakar and Researcher on Open-Source Software’s",
    },
    {
      id: 8,
      category: "experience",
      icon: "icon-briefcase",
      year: " September 2009 – September 2010",
      title: "Instructor at ULK",
      desc: "Instructor of computer skills at Kigali Independent University and  Consultant in IT services, Telecom services, Computer maintenance and user support",
    },
    {
      id: 9,
      category: "experience",
      icon: "icon-briefcase",
      year: " October 2010 – October 2012",
      title: "IT Officer at UNIVERSITY OF GITWE",
      desc: "With addition to being an IT Instructor at KIGALI INDEPENDENT UNIVERSITY",
    },
    {
      id: 10,
      category: "experience",
      icon: "icon-briefcase",
      year: "October 2012 – October 2017",
      title: " IT Instructor at UNIVERSITY OF RWANDA",
      desc: "And an IT Instructor and statistical software trainer at KIGALI INDEPENDENT UNIVERSITY",
    },
    {
      id: 11,
      category: "experience",
      icon: "icon-briefcase",
      year: "October 2017 Up to now",
      title: "Ag. Head of IT Department, School of ICT, College of Science and Technology at UNIVERSITY OF RWANDA",
      desc: "And a Web administrator and IT consultant at NPIA-KIGALI",
    },
  ];
  

export default Data